### ISSUE TITLE
Plugin assumptions

### ISSUE THREAD

**Issue by cameronjroe** [superwolff/metalsmith-in-place#32]
This plugin assumes that a `src` directory will contain templates that one wouldn't otherwise put in layouts for rendering specifically as in-place templates in that `src` directory. It's somewhat strange to me because I put all my layouts/in-place templates in my src directory and render the adjacent directories that contain markdown and content. Considering that `src` is typically used in contrast to `dist`, would it be reasonable to say that all files that should be processed would be in `src` including layouts and in-place templates? This would mean that layouts and in-place are effectively part of the same processing that happens on other `src` files. I realize that there used to be a `metalsmith-templates` that took care of both of these. I honestly think that makes more sense because splitting layouts outside of `src` seems to be somewhat confusing.

I think something like this would make a ton of sense:
```
- src/
  - templates/
    - layouts/ -> layouts that use includes
    - includes/ -> includes that go in layouts
    - template.liquid -> arbitrary template that's rendered from using it's name
```

This way you know where everything is, and it's actually handling one responsibility, rendering templates.

Metadata could be:
```
layout: layout-name
or 
template: template
```

**Comment by ismay** [comment]
> This plugin assumes that a src directory will contain templates that one wouldn't otherwise put in layouts for rendering specifically as in-place templates in that src directory.

Not really. The only thing that this plugin does is process the files that are passed to it by metalsmith. Metalsmith itself has some default folders (src and build), but you can change that.

Other than that the templating engines might have some different ways to deal with includes and extends (relative vs absolute), but otherwise the structure is completely up to you.

That being said, I would advise against putting your templates in src because your templates aren't the actual content, they're just used to render the content. But it's up to you. Have a look at [metalsmith-boilerplates](https://github.com/superwolff/metalsmith-boilerplates/tree/in-place/complete) if you want to see an example.

Closing as the issue does not seem to be an issue with metalsmith-in-place itself. If not, please rephrase what you think the bug is, as that isn't really clear right now.
