### ISSUE TITLE
Relative path for partials/pattern 

### ISSUE THREAD

**Issue by gunnx** [superwolff/metalsmith-in-place#43]
It looks like partials is relative to root, while pattern is relative to src

**Comment by doodzik** [comment]
can you provide additional informations how you set it up?
If you don't want it to be public you can email it to me.
I'm going to look into it and reopen this issue as soon as I get the information :)

**Comment by gunnx** [comment]
Here is extract of my config:
```
Metalsmith(__dirname)
.use(inplace({
    engine: 'handlebars',
    partials: 'src/partial',
    pattern: 'page/*.hbs',
    rename: true
  }))
```

The partials is relative to the where I ran the build from while pattern is relative to the default Metalsmith folder, which is `src` in my case.

**Comment by ismay** [comment]
> The partials is relative to the where I ran the build from while pattern is relative to the default Metalsmith folder, which is src in my case.

That's intentional. The reason being that you don't want your partials to end up in your `dist` (since they're only partials and not complete files meant for output). So we let you choose where your partials are in your project folder (which should be outside of `src`).

The pattern is relative to `src` because it doesn't make sense to use a pattern outside of `src`, since metalsmith only processes files from `src`.

I understand how this can be confusing, because your approach works, as you're filtering out the partials with the pattern, but that is by no means the recommended approach. The way this is meant to be used is by putting your partials outside of `src`.

**Comment by ismay** [comment]
@doodzik Maybe we should document this more clearly in the readme. I've now come across several cases where people are putting layouts and partials in src, which in my opinion isn't something we want to support.

**Comment by gunnx** [comment]
Thanks for the explanation, I'm used to putting all my source code under src so I include partials in there too, as you noticed I keep my pages separate from my partials. 
I'd say just a bit more in the readme will do the job.

**Comment by doodzik** [comment]
I think it makes sense to separate them, but we definitely want to add that to the readme.

**Comment by doodzik** [comment]
@ismay should we do it as a point in a faq?

**Comment by ismay** [comment]
Hmm yeah, we could also add it to the `pattern` and `partials` sections, but it might not be noticed there. A faq seems like a good idea :+1:
