### ISSUE TITLE
Decouple file extension and template engine/transformer

### ISSUE THREAD

**Issue by johanbrook** [superwolff/metalsmith-in-place#78]
Hey! Thanks for this plugin.

One issue I have is the tight coupling between a file extension (ex. `.html.hbs`) and its corresponding transformer (ex. `jstransformer-handlebars`). I'm using the `metalsmith-permalinks` plugin, and it's **not building proper permalinks from templates if they're not a `.html` file** ([source](https://github.com/segmentio/metalsmith-permalinks/blob/master/lib/index.js#L72)).

So. I can't use `.html` for my templates since this plugin won't transform them with Handlebars, and I can't use `.html.hbs` in order to get pretty permalinks.

I've tried putting the `.use(permalinks())` call both before and after my `inPlace()` call. I noted that `inPlace` is behaving differently from `metalsmith-markdown`, for instance. The Markdown plugin will process an `.md` file to HTML and pass it to `permalinks`, but `inPlace` doesn't seem to process `.html.hbs` files to HTML at once and pass to `permalinks`:

```
src/
   lol.md
```

```js
// ...
.use(markdown())
.use(permalinks());
```

Turns into

```
build/
   lol/
      index.html
```

since `permalinks` already got a `lol.html` to play with (I debugged the output).

It would be super cool if we could override a certain extension to be transformed with a certain transformer:

```js
.use(inPlace({
  transformer: 'jstransformer-handlebars'
}))
```

I realise this is trickling down in to the other repo (https://github.com/superwolff/metalsmith-engine-jstransformer/blob/master/lib/render-file.js#L36), but the option needs to live up here I guess.

**Comment by ismay** [comment]
Hi,

Glad you like it. Unfortunately jstransformers kind of revolve around file extensions, and to circumvent that would break the whole jstransformer idea.

You should be able to solve this easily by running metalsmith-permalinks after in-place. Since in-place has then already renamed the files to .html metalsmith-permalinks shouldn't have any problems.

Let me know if that works!

**Comment by johanbrook** [comment]
Whoa, it works now 🎉 I put it like this in my build file:

```js
.use(inPlace())

  .use(permalinks({
    relative: false
  }))

  .use(layouts({
    directory: 'src/layouts',
    partials: 'src/partials',
    pattern: '**/*.html',
    engine: 'handlebars',
    default: 'layout.html'
  }));
```

Before, I had put `permalinks()` below the call to `layouts()`.

Thanks for taking the time!

**Comment by ismay** [comment]
> The Markdown plugin will process an .md file to HTML and pass it to permalinks, but inPlace doesn't seem to process .html.hbs files to HTML at once and pass to permalinks:

What do you mean exactly? Because in-place processes all files, and only when it's done with all of them will the next plugin in the chain be started. Which is how all metalsmith plugins should handle files.

And if you're processing say `index.html.hbs`, in-place should process it and rename it to `index.html`. Is it not doing that?

**Comment by ismay** [comment]
Ha, posted at the same time again. Great! Glad that it worked out!
