### ISSUE TITLE
Cannot get simple example to work

### ISSUE THREAD

**Issue by Zearin** [superwolff/metalsmith-in-place#87]
Sigh…in order to try the JSTransformer file extension-based approach, I set up a minimal test.  It has failed. :( 

Here’s what I have in the project directory:

```
# the usual stuff (`package.json`, `node_modules/`, etc. etc.)
index.js
- src/
  - content/
    index.html.markdown
```

Here’s what I get from `npm ls --depth=0`:

```
metalsmith-inplace-test@1.0.0 «HOME»/metalsmith-inplace-test
├── jstransformer-markdown@1.1.1
├── jstransformer-pug@0.2.3
├── metalsmith@2.3.0
├── metalsmith-in-place@2.0.1
└── metalsmith-layouts@1.8.1
```

Here’s `index.js`:

```javascript
#!/usr/bin/env node

//  metalsmith and plugins
const Metalsmith = require('metalsmith')
const inplace    = require('metalsmith-in-place')

// I was planning to test this example with layouts next, but
// I can't even get this simple bit of code working. >:(
//const layouts    = require('metalsmith-layouts')

let pluginInplace = inplace({
    //engineOptions:  {},
    pattern:    `${__dirname}/src/content/**`
})

//  instantiate
const metalsmith    = Metalsmith(__dirname)
    .clean(true)
    .use(pluginInplace)
    .build(function(err)  {
        if (err) throw err;
    })
```

When I run this script, it just copies the source document to the `build/` directory…**completely unchanged**.  

What am I doing wrong???

**Comment by ismay** [comment]
I don't know. The issues aren't meant for troubleshooting builds, only for reporting bugs. The unit tests are all passing so try to look there if you need examples. Otherwise, I suggest you create a reduced testcase and ask your question on stack overflow. Should you find any bugs in this library then feel free to report them here!

**Comment by Zearin** [comment]
Okay…

I may have phrased this as a support request.  My mistake.  

However, I believe this actually _is_ a bug.  

Here’s why:

- According to the README, the default engine is `metalsmith-engine-jstransformer`
- This engine is supposed to perform transformations based on file extensions
- After each transformation, the last file extension should be removed until all “extra” file extensions are done (OR there are no appropriate JSTransformers installed)

What I describe above is a straightforward case in which this behavior is **not occurring**.

**Comment by ismay** [comment]
Try changing your pattern. That's why it's failing. If you remove it it'll work. the reason it's failing is because metalsmith only processes files from .source() (default `src`), so all paths are automatically relative to `src` already.

So the path you've given doesn't match anything and it's working as expected.

**Comment by Zearin** [comment]
@ismay _I owe you an apology_ …and my thanks.  

I’m not sure how I missed that. It really was that simple.  

Feeling humble.  I will remember this lesson. :)

Thank you once again!

**Comment by ismay** [comment]
No problem at all, we've all been there 👍
